[project]
authors = ["Antonio Camargo <antoniop.camargo@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = " Retrieve and parse metadata retrieved from the ENA"
name = "retrieve-ena-metadata"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
pycountry = ">=24.6.1,<25"
requests = ">=2.32.3,<3"
taxopy = ">=0.13.0,<0.14"
pydantic = ">=2.9.1,<3"
pydantic-extra-types = ">=2.8.2,<3"
ipykernel = ">=6.29.5,<7"
pixi-kernel = ">=0.4.0,<0.5"
